### PR TITLE
Fix/import nitro

### LINKED ISSUE #404: Version 2.0 does not import 'nitro'
### Current behavior
Users have to managed nitro version

### Expected behavior
The package should manage its own nitro module

### PR DESCRIPTION
**Pull request by HuuNguyen312**
## Summary
  
  Fixes #404.

  On older React Native versions, the Android build of the Nitro module fails to compile with:
  
  Class 'NitroPromiseAdapter' is not abstract and does not implement abstract members:
  fun reject(code: String, message: String?): Unit
  fun reject(code: String, throwable: Throwable?): Unit
  fun reject(code: String, message: String?, throwable: Throwable?): Unit
  fun reject(code: String, userInfo: WritableMap): Unit
  fun reject(code: String, throwable: Throwable?, userInfo: WritableMap): Unit
  fun reject(code: String, message: String?, userInfo: WritableMap): Unit

  **Why this happens — a React Native version difference, surfaced by Kotlin's type rules:**

  The bridge `Promise` interface declares the `code` parameter of `reject(...)` differently across RN versions:

  | React Native | `code` in `reject(...)` |
  | --- | --- |
  | Older RN | `code: String` — **non-null** |
  | RN 0.85 | `code: String?` — **nullable** |
  
  `NitroPromiseAdapter` was written in Kotlin with `code: String?` to match RN 0.85. Since **Kotlin override parameter types are invariant**, a single Kotlin source can only match *one* nullability variant — it compiles on RN 0.85 but breaks on
  older RN (the 6 overloads above stop counting as "implemented"). No single Kotlin source can satisfy both ranges at once.

  **The fix:** Rewrite `NitroPromiseAdapter` in **Java**. Java erases nullability annotations when matching overrides, so one Java implementation satisfies the `reject(...)` contract on *every* RN version — matching the library's `"react-native":
  "*"` peer range. The adapter is the only class in the repo that implements the bridge `Promise`; the single construction site in `HybridCompressor.kt` needs no change because the Kotlin lambdas (`(Any?) -> T`, `() -> Unit`) flow straight into
  the Java `Function1` / `Function0` constructor params.
  
  ## Changelog

  [ANDROID] [FIXED] - Rewrite `NitroPromiseAdapter` in Java so the Nitro module compiles across all React Native versions (older RN declared `Promise.reject`'s `code` as non-null, RN 0.85 as nullable; Kotlin's invariant override params could not
  satisfy both) (#404)

  ## Test Plan
  
  - [x] Ran local JS PR gate: `yarn test:pr`

  Test Suites: 1 passed, 1 total
  Tests:       13 passed, 13 total
  ✖ 9 problems (0 errors, 9 warnings)   # pre-existing warnings only
  typecheck: pass

  
  - [x] Library module compiles (Kotlin call site + new Java adapter) on RN 0.85:

  ./gradlew :react-native-compressor:compileDebugKotlin :react-native-compressor:compileDebugJavaWithJavac
  BUILD SUCCESSFUL
  
  - [x] Ran Harness on Android (`Pixel_9a` emulator, rebuilt debug APK):

  yarn test:harness:android
  Test Suites: 1 passed, 1 total
  Tests:       9 passed, 9 total
  
  - [x] Ran Harness on iOS (iPhone 17 Pro / iOS 26.4) as a regression check (iOS native untouched):

  yarn test:harness:ios
  Test Suites: 1 passed, 1 total
  Tests:       9 passed, 9 total

  > Note: the failing path (non-null `code`) is the older-RN signature reported in #404. It can't be compiled on this machine since the repo targets RN 0.85, but the Java-erasure approach is exactly what makes the adapter valid across both
  signature variants.

### CODE REVIEW

**Review by numandev1 — APPROVED** [review]
Thanks
