### ISSUE TITLE
iOS build fails on 1.17.0 — `value of type 'NextLevelSessionExporter' has no member 'error'`

### ISSUE THREAD

**Issue by nthtrung09it** [Shobbak/react-native-compressor#394]
## Description

After upgrading from 1.16.2 → 1.17.0, the iOS build fails to compile with a Swift type-check error in `ios/Video/VideoMain.swift`. The reference to `exporter.error` does not exist on `NextLevelSessionExporter`.

## Error

```
node_modules/react-native-compressor/ios/Video/VideoMain.swift:354:36: error:
  value of type 'NextLevelSessionExporter' has no member 'error'
                onFailure(exporter.error ?? CompressionError(message: "Compression failed"))
                          ~~~~~~~~ ^~~~~
```

There is a related warning a few lines below:

```
ios/Video/VideoMain.swift:421:11: warning: 'catch' block is unreachable because
no errors are thrown in 'do' block
```

## Reproduction

1. Install `react-native-compressor@1.17.0` in any RN project.
2. `pod install` (or `pnpm pods` in a monorepo).
3. Build the iOS app from Xcode (or `xcodebuild`).
4. Build fails with the above type-check error.

## Bisect

The error is introduced in PR #392 (commit `afa4da712bcd4d666adc5815037a51ef1c3d16dd`, *"Triage issues and harden high-resolution video compression paths"*) — the only commit between `v1.16.2` and `v1.17.0` that touches `ios/Video/VideoMain.swift`.

The new completion handler `default:` branch references `exporter.error`:

```swift
default:
    onFailure(exporter.error ?? CompressionError(message: "Compression failed"))
    break
```

…but `NextLevelSessionExporter` does not expose an `error` property — only `status: AVAssetExportSession.Status`. The Swift compiler rejects it.

## Suggested fix

Replace with a status-aware generic failure, e.g.:

```swift
default:
    onFailure(CompressionError(message: "Compression failed (status: \(exporter.status.rawValue))"))
    break
```

If the intent was to surface an underlying `Error?` from the export callback, that needs to be captured in a `var lastError: Error?` inside `export(...)` rather than queried from the exporter object.

## Workaround

Pin to 1.16.2:

```json
"react-native-compressor": "1.16.2"
```

## Environment

- react-native-compressor: **1.17.0**
- react-native: 0.85.2 (New Architecture, Fabric, Hermes)
- iOS deployment target: 15.5
- Xcode: 26.4.1 (Build 17E202)
- macOS: 26.4.1
- CocoaPods: 1.15.2 (project) / 1.16.2 (system)

**Comment by Izocel** [comment]
Error with 1.18 also:

<img width="1171" height="245" alt="Image" src="https://github.com/user-attachments/assets/268a65c7-5328-4220-8c6e-4d7950620a77" />

**Comment by numandev1** [comment]
@usama-liaqat can you test it on your side?

**Comment by numandev1** [comment]
can you try `1.18.1`

**Comment by nthtrung09it** [comment]
Tks, It works with v1.18.1
